/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Batch */
        post: operations["create_batch_api_batches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Batch */
        get: operations["get_batch_api_batches__batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches/{batch_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Batch Events */
        get: operations["get_batch_events_api_batches__batch_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches/{batch_id}/refine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refine Batch
         * @description Generate a child batch from this batch's approve/reject feedback.
         */
        post: operations["refine_batch_api_batches__batch_id__refine_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches/{batch_id}/select-final": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Select Final */
        post: operations["select_final_api_batches__batch_id__select_final_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/{candidate_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Candidate */
        get: operations["get_candidate_api_candidates__candidate_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/{candidate_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Candidate */
        post: operations["approve_candidate_api_candidates__candidate_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/{candidate_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject Candidate */
        post: operations["reject_candidate_api_candidates__candidate_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/candidates/{candidate_id}/variant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Variant */
        post: operations["request_variant_api_candidates__candidate_id__variant_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/doctor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Doctor */
        get: operations["doctor_api_doctor_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Lessons
         * @description Top-N refinement lessons ranked by improvement_delta (ZREVRANGE).
         */
        get: operations["list_lessons_api_lessons_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/taste": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Taste Profile
         * @description The producer's taste profile: active backend + semantically recalled facts.
         *
         *     ``facts`` come from the taste backend (Agent Memory semantic search, or local
         *     lesson recall). ``lessons`` are the legacy Redis sorted-set audit trail.
         */
        get: operations["taste_profile_api_taste_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/taste/recall": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Taste Recall
         * @description Preview the taste recall + derived planning bias a brief would receive.
         *
         *     This is exactly what ``start_batch`` applies before generating, exposed for
         *     the UI/demo so you can see *why* a fresh batch leans the way it does.
         */
        get: operations["taste_recall_api_taste_recall_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Batch */
        Batch: {
            /** Batch Id */
            batch_id: string;
            brief: components["schemas"]["CreativeBrief"];
            /** Candidate Ids */
            candidate_ids?: string[];
            /** Candidates */
            candidates?: components["schemas"]["Candidate"][];
            /** Created At */
            created_at?: string;
            /** Events */
            events?: components["schemas"]["BatchEvent"][];
            /** Parent Batch Id */
            parent_batch_id?: string | null;
            /** Selected Final Id */
            selected_final_id?: string | null;
            /**
             * Status
             * @default running
             * @enum {string}
             */
            status: "running" | "ranked" | "completed" | "failed";
        };
        /** BatchCreateRequest */
        BatchCreateRequest: {
            brief: components["schemas"]["CreativeBrief"];
        };
        /** BatchEvent */
        BatchEvent: {
            /** Id */
            id?: string;
            /** Message */
            message: string;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            };
            /** Ts */
            ts?: string;
            /** Type */
            type: string;
        };
        /**
         * Candidate
         * @description One generated piece of music plus its score, artifacts, and curation state.
         */
        Candidate: {
            /** Arrangement Url */
            arrangement_url?: string | null;
            /** Audio Url */
            audio_url?: string | null;
            /** Batch Id */
            batch_id: string;
            /** Candidate Id */
            candidate_id: string;
            /** Created At */
            created_at?: string;
            /** Drum Kit */
            drum_kit?: {
                [key: string]: unknown;
            };
            /** Feedback */
            feedback?: string | null;
            /** Internal Prompt */
            internal_prompt?: string | null;
            /** Key */
            key: string;
            /** Midi Urls */
            midi_urls?: {
                [key: string]: string;
            };
            /** Mode */
            mode: string;
            /** Parent Candidate Id */
            parent_candidate_id?: string | null;
            /** Parent Profile Id */
            parent_profile_id?: string | null;
            /**
             * Policy Version
             * @default 0
             */
            policy_version: number;
            /** Profile Features */
            profile_features?: {
                [key: string]: number;
            };
            /** Profile Id */
            profile_id?: string | null;
            /** Prompt Policy */
            prompt_policy?: {
                [key: string]: unknown;
            };
            /** Reasons */
            reasons?: string[];
            /** Scores */
            scores?: {
                [key: string]: unknown;
            };
            /** Seed */
            seed: number;
            /** Sound Profile */
            sound_profile?: {
                [key: string]: unknown;
            };
            /**
             * Status
             * @default generated
             * @enum {string}
             */
            status: "generated" | "approved" | "rejected" | "variant_requested" | "final";
            /** Strategy */
            strategy: string;
            /**
             * Technical Score
             * @default 0
             */
            technical_score: number;
            /** Tempo */
            tempo: number;
            /** Trace Url */
            trace_url?: string | null;
            /** Voices */
            voices?: {
                [key: string]: string;
            };
            /** Weave Call Id */
            weave_call_id?: string | null;
        };
        /**
         * CreativeBrief
         * @description What the operator asks for. One brief → many candidates.
         */
        CreativeBrief: {
            /**
             * Candidate Count
             * @default 4
             */
            candidate_count: number;
            /**
             * Energy
             * @default 0.5
             */
            energy: number;
            /**
             * Key
             * @default F#
             */
            key: string;
            /**
             * Mode
             * @default minor
             * @enum {string}
             */
            mode: "major" | "minor";
            /** Prompt */
            prompt: string;
            /** Taste Constraints */
            taste_constraints?: string[];
            /**
             * Tempo
             * @default 128
             */
            tempo: number;
        };
        /** DoctorResponse */
        DoctorResponse: {
            /** Checks */
            checks: {
                [key: string]: boolean;
            };
            /** Notes */
            notes?: string[];
            /** Ok */
            ok: boolean;
            /** Orchestration */
            orchestration?: {
                [key: string]: unknown;
            };
        };
        /** FeedbackRequest */
        FeedbackRequest: {
            /**
             * Note
             * @default
             */
            note: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** RefineRequest */
        RefineRequest: {
            /** Candidate Count */
            candidate_count?: number | null;
        };
        /** SelectFinalRequest */
        SelectFinalRequest: {
            /** Candidate Id */
            candidate_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_batch_api_batches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Batch"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_batch_api_batches__batch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Batch"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_batch_events_api_batches__batch_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchEvent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refine_batch_api_batches__batch_id__refine_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RefineRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Batch"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    select_final_api_batches__batch_id__select_final_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelectFinalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Batch"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_candidate_api_candidates__candidate_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Candidate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_candidate_api_candidates__candidate_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Candidate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_candidate_api_candidates__candidate_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Candidate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_variant_api_candidates__candidate_id__variant_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                candidate_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Candidate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    doctor_api_doctor_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DoctorResponse"];
                };
            };
        };
    };
    list_lessons_api_lessons_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    taste_profile_api_taste_get: {
        parameters: {
            query?: {
                limit?: number;
                prompt?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    taste_recall_api_taste_recall_get: {
        parameters: {
            query: {
                prompt: string;
                key?: string;
                mode?: string;
                tempo?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
